from RecsysStats import RecSysStats
rcStats = RecSysStats('/mnt/training.tsv')
#rcStats.generate_language_encoding('/mnt/val.tsv')
#rcStats.generate_user_features('/mnt/val.tsv')
rcStats.count_pseudo_negative()
#rcStats.get_all_retweet('/mnt/val.tsv')
#rsUtils = RecSysUtility('/mnt/val.tsv')
#rsUtils.exploit_leaks_retweet('prediction_Retweet.csv', 'retweet_100.csv')
#rcUtils.count_n_lines()
#rcUtils.count_n_tweets(isVal=True)
#rcUtils.user_or_author(isVal=True)
#rcUtils.count_action_type('Retweet_with_comment', isVal=True)
#rcUtils.count_action_type('Retweet', isVal=True)
#rcUtils.count_action_type('Reply', isVal=True)
#rcUtils.count_action_type('Like', isVal=True)
